QUICKSTART.md
README.md

Updating `README` and `Quickstart`

updating the getting started experience

---

.github/workflows/test_common.yml
.github/workflows/test_loader_gcp.yml
.github/workflows/test_loader_redshift.yml
dlt/common/file_storage.py
dlt/common/logger.py
dlt/common/normalizers/json/relational.py
dlt/common/schema/detections.py
dlt/common/schema/schema.py
dlt/common/schema/typing.py
dlt/common/schema/utils.py
dlt/common/storages/loader_storage.py
dlt/common/utils.py
dlt/common/validation.py
dlt/dbt_runner/runner.py
dlt/dbt_runner/utils.py
dlt/unpacker/unpacker.py
examples/quickstart.py
examples/sources/singer_tap.py
poetry.lock
pyproject.toml
tests/common/normalizers/test_json_relational.py
tests/common/schema/test_coercion.py
tests/common/schema/test_detections.py
tests/common/schema/test_inference.py
tests/common/storages/test_file_storage.py
tests/common/test_utils.py
tests/dbt_runner/test_utils.py
tests/test_validation.py
tests/unpacker/test_unpacker.py
tests/utils.py

See the tickets below for instruction how to use those new features in the schema
- closes #37 
- closes #41 
- closes #45

adds nesting limit, normalizing list of lists and type autodetections to json normalizer

---

dlt/cli/dlt.py
dlt/common/json.py
dlt/common/schema/utils.py
dlt/common/storages/load_storage.py
dlt/common/storages/normalize_storage.py
dlt/load/bigquery/client.py
dlt/load/dummy/client.py
dlt/load/load.py
dlt/load/redshift/client.py
dlt/load/typing.py
dlt/normalize/normalize.py
dlt/pipeline/pipeline.py
experiments/pipeline/pipeline.py
experiments/pipeline/sources.py
poetry.lock
pyproject.toml
tests/common/schema/test_coercion.py
tests/common/storages/test_loader_storage.py
tests/load/bigquery/test_bigquery_client.py
tests/load/cases/long_names.json
tests/load/redshift/test_redshift_client.py
tests/load/test_client.py
tests/load/utils.py
tests/utils.py

* fixes pendulum date parsing
* adds pypy support for redshift
* adds identifier and column lengths to capabilities
* tests column and table name lengths in redshift

fixes pendulum date parsing

---

dlt/__init__.py
dlt/common/configuration/accessors.py
dlt/destinations/bigquery/sql_client.py
dlt/destinations/postgres/sql_client.py
dlt/pipeline/state.py
docs/pipeline/examples/create_pipeline.md
docs/pipeline/examples/general_usage.md
docs/pipeline/examples/multistep_pipelines_and_transformers.md
docs/pipeline/examples/secrets_and_config.md
docs/pipeline/examples/working_with_schemas.md
examples/chess/chess.py
tests/load/postgres/test_postgres_common.py
tests/load/test_sql_client.py
tests/load/utils.py

1. some improvements to proposal docs
2. sql client fixes
3. config and secrets placeholders

proposal docs and fixes

---

dlt/cli/_dlt.py
dlt/common/exceptions.py
dlt/common/json.py
dlt/common/logger.py
dlt/common/normalizers/exceptions.py
dlt/common/normalizers/json/relational.py
dlt/common/runners/pool_runner.py
dlt/common/schema/utils.py
dlt/common/time.py
dlt/common/utils.py
dlt/extract/decorators.py
dlt/extract/extract.py
dlt/normalize/normalize.py
dlt/pipeline/configuration.py
dlt/pipeline/exceptions.py
dlt/pipeline/pipeline.py
dlt/reflection/script_inspector.py
examples/chess/chess.py
pyproject.toml
tests/cli/test_cli.py
tests/common/normalizers/test_json_relational.py
tests/common/runners/test_runners.py
tests/common/schema/test_coercion.py
tests/common/test_logging.py
tests/common/test_utils.py
tests/extract/test_decorators.py
tests/load/pipeline/test_pipelines.py
tests/pipeline/test_pipeline.py
tests/utils.py

usability improvements

---

dlt/common/data_writers/buffered.py

This solves https://github.com/dlt-hub/dlt/issues/126 for me

Fix current columns and new columns referencing the same object

---

dlt/helpers/streamlit.py
docs/website/docs/command-line-interface.md
docs/website/docs/getting-started.md
docs/website/docs/installation.mdx

Changes getting started to use DuckDB rather than Google BigQuery

getting started: bigquery --> duckdb

---

dlt/cli/init_command.py
dlt/cli/utils.py
dlt/common/normalizers/naming/duck_case.py
dlt/common/normalizers/naming/snake_case.py
dlt/reflection/script_inspector.py
pyproject.toml
tests/common/normalizers/test_json_relational.py
tests/common/normalizers/test_naming_duck_case.py
tests/common/normalizers/test_naming_snake_case.py
tests/common/schema/test_schema.py
tests/extract/test_decorators.py

* fixes problem with init module import
* fixes the snake case naming convention

dlt init post release

---

docs/website/docusaurus.config.js

this puts a hyperlink to the github repo in the bottom left of each docs page

add `edit this page` button on all docs pages

---

.github/workflows/get_docs_changes.yml
.github/workflows/lint.yml
.github/workflows/skip_docs_changes.yml
.github/workflows/test_common.yml
.github/workflows/test_dbt_runner.yml
.github/workflows/test_destination_bigquery.yml
.github/workflows/test_destinations.yml

Optimize CI pipeline by skipping tests when changes are limited to the docs folder. 
Closes: #213

CI: Skip running tests when only docs changes are detected

---

docs/website/docs/architecture.md
docs/website/docs/command-line-interface.md
docs/website/docs/concepts/import-dlt.mdx
docs/website/docs/concepts/pipeline.md
docs/website/docs/concepts/resource.md
docs/website/docs/concepts/source.md
docs/website/docs/concepts/state.md
docs/website/docs/customization/credentials.md
docs/website/docs/customization/incremental-loading.md
docs/website/docs/destinations.md
docs/website/docs/getting-started.md
docs/website/docs/glossary.md
docs/website/docs/installation.mdx
docs/website/docs/intro.md
docs/website/docs/pipelines/github.md
docs/website/docs/pipelines/google_sheets.md
docs/website/docs/pipelines/pipedrive.md
docs/website/docs/pipelines/strapi.md
docs/website/docs/reference/telemetry.md
docs/website/docs/reference/tracing.md
docs/website/docs/running-in-production/orchestrators/airflow-gcp-cloud-composer.md
docs/website/docs/running-in-production/orchestrators/choosing-an-orchestrator.md
docs/website/docs/running-in-production/running.md
docs/website/docs/using-loaded-data/transforming-the-data.md
docs/website/docusaurus.config.js

See https://docusaurus.io/docs/next/seo for SEO suggestions

improving seo of docs

---

docs/website/docs/pipelines/chess.md
docs/website/sidebars.js

adding the chess pipeline documentation

---

dlt/common/json/__init__.py
dlt/common/json/_orjson.py
dlt/common/json/_simplejson.py
dlt/common/utils.py
dlt/destinations/job_client_impl.py
dlt/extract/incremental.py
dlt/pipeline/pipeline.py
dlt/pipeline/state_sync.py
mypy.ini
tests/cases.py
tests/common/schema/test_coercion.py
tests/common/test_json.py
tests/extract/test_incremental.py
tests/load/pipeline/test_restore_state.py

https://github.com/dlt-hub/dlt/issues/180
TODO: Tests

Typed pipeline state

---

.github/workflows/get_docs_changes.yml

CI: Fix incorrectly detected changes

---

docs/website/docusaurus.config.js

https://docsearch.algolia.com/

adds Agolia DocSearch to the dlt docs 🚀

---

.github/workflows/test_common.yml

This PR attempts to fix the handling of matrix job results in our GitHub Actions workflow. 
The PR introduce a collector job for the matrix job results to ensures that the required status check in the branch protection rules accurately reflect the success or failure of the matrix jobs.
Details:
https://github.com/actions/runner/issues/952
https://github.com/orgs/community/discussions/9141

Update GitHub Actions workflow to handle matrix job results

---

.github/workflows/test_common.yml
.github/workflows/test_dbt_runner.yml
.github/workflows/test_destination_bigquery.yml
.github/workflows/test_destinations.yml

Expand #256 to every CI workflow containing matrix

Add matrix collectors to every test_* workflow

---

dlt/common/schema/typing.py
dlt/common/schema/utils.py
dlt/extract/schema.py
tests/common/cases/schemas/eth/ethereum_schema_v5.yml
tests/common/schema/test_schema.py
tests/common/utils.py
tests/pipeline/test_pipeline.py

Resolves https://github.com/dlt-hub/dlt/issues/210

add resource name to table schema

---

docs/website/docs/using-loaded-data/transforming-the-data.md

updating the documentation for the section 'Transforming the data'

---

dlt/common/pipeline.py
dlt/common/utils.py
dlt/extract/decorators.py
dlt/extract/incremental.py
dlt/extract/source.py
dlt/helpers/streamlit.py
dlt/pipeline/pipeline.py
docs/website/docs/general-usage/incremental-loading.md
docs/website/docs/general-usage/resource.md
tests/common/cases/modules/uniq_mod_121.py
tests/common/test_utils.py
tests/extract/test_incremental.py
tests/load/pipeline/utils.py

this avoids modification of pipeline stored schemas before extract step completes successfully

clones and updates pipeline schemas after extract

---

README.md
docs/website/docusaurus.config.js

pushing the new colab demo

---

docs/website/docusaurus.config.js

see here for context: https://dlthubinc.slack.com/archives/C05409H5X0W/p1682429538342249

adding another google tag id

---

docs/website/docs/intro.md

based off of https://www.notion.so/dlthub/4-24-Docs-intro-README-refactor-568740318c914f2e851d7b2fae0b3a0c

refactored intro

---

docs/website/docs/pipelines/hubspot.md

Added a step to configure secrets.toml please check @adrianbr @TyDunn & @rahuljo

Updated "Add credentials" a step to configure secrets.toml

---

CONTRIBUTING.md
README.md

This pull request separates the contributing guidelines from the main README.md file and updates the README.md as well.

Update README, add contributor's guide

---

dlt/cli/deploy_command.py
dlt/cli/init_command.py
dlt/cli/pipeline_files.py
dlt/common/configuration/accessors.py
dlt/common/configuration/paths.py
dlt/common/configuration/providers/google_secrets.py
dlt/common/configuration/providers/toml.py
dlt/common/configuration/resolve.py
dlt/common/configuration/specs/config_providers_context.py
dlt/common/normalizers/json/relational.py
dlt/common/pipeline.py
dlt/common/runtime/exec_info.py
dlt/common/runtime/segment.py
dlt/common/storages/file_storage.py
dlt/common/storages/load_storage.py
dlt/extract/decorators.py
dlt/helpers/airflow.py
dlt/helpers/pandas.py
dlt/pipeline/pipeline.py
dlt/sources/helpers/requests/retry.py
pyproject.toml
tests/cli/test_init_command.py
tests/common/configuration/test_toml_provider.py
tests/common/normalizers/test_json_relational.py
tests/common/storages/test_file_storage.py
tests/conftest.py
tests/helpers/airflow_tests/test_airflow_provider.py
tests/normalize/test_normalize.py
tests/sources/helpers/test_requests.py

fixes various airflow deployment issues

---

docs/website/docs/pipelines/asana.md
docs/website/sidebars.js

Please review @adrianbr , @TyDunn & @rahuljo

Adding asana dlt setup guide

---

docs/website/docs/pipelines/shopify.md
docs/website/sidebars.js

Adding shopify docs

---

docs/website/docs/pipelines/asana.md

Fixes: #343
Minor updates to correct the typo in asana.md doc

Fix typo in docs/pipelines/asana.md

---

docs/website/docs/pipelines/google_sheets.md

Fix broken link in docs/website/docs/pipelines/google_sheets.md

---

docs/website/docusaurus.config.js

https://docusaurus.io/docs/markdown-features/code-blocks
Added languages: python, toml, shell etc.

Highlight code in docusaurus.config.js

---

docs/website/blog/2023-06-14-dlthub-gpt-accelerated learning_01.md

I found the mistake for questions - " "

change " "  for questions

---

docs/website/docs/dlt-ecosystem/verified-sources/salesforce.md
docs/website/sidebars.js

Please review @AstrakhantsevaAA

Added salesforce docs

---

dlt/cli/_dlt.py
dlt/cli/pipeline_files.py
dlt/common/data_writers/buffered.py
dlt/common/data_writers/writers.py
dlt/common/storages/file_storage.py
dlt/destinations/insert_job_client.py
dlt/destinations/job_client_impl.py
dlt/pipeline/trace.py
docs/examples/discord_iterator.py
tests/common/storages/test_file_storage.py
tests/common/test_data_writers/test_buffered_writer.py
tests/common/utils.py
tests/load/bigquery/test_bigquery_client.py
tests/load/pipeline/test_pipelines.py
tests/load/utils.py
tests/normalize/test_normalize.py
tests/normalize/utils.py
tests/pipeline/utils.py

Adds compression support
closes #388

Feat: Use compression to maximize network and disk space efficiency

---

docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-airflow-composer.md

Docs: fix airflow deploy

---

docs/website/docs/dlt-ecosystem/destinations/redshift.md

Please Review, @AstrakhantsevaAA, @rudolfix. Thanks!

Updated Redshift.md

---

docs/website/docs/dlt-ecosystem/verified-sources/chess.md
docs/website/docs/running-in-production/alerting.md
docs/website/docs/running-in-production/running.md
docs/website/docs/running-in-production/tracing.md

Please review @AstrakhantsevaAA; it's according to the new structure.

Updated Chess Docs

---

dlt/cli/echo.py
dlt/cli/init_command.py
dlt/cli/pipeline_files.py
dlt/cli/requirements.py
tests/cli/test_init_command.py

Implements: https://github.com/dlt-hub/dlt/issues/241

dlt init version check

---

dlt/common/destination/reference.py
dlt/common/schema/exceptions.py
dlt/common/schema/schema.py
dlt/destinations/bigquery/bigquery.py
dlt/destinations/duckdb/duck.py
dlt/destinations/motherduck/motherduck.py
dlt/destinations/postgres/postgres.py
dlt/destinations/redshift/redshift.py
dlt/destinations/snowflake/snowflake.py
dlt/destinations/weaviate/configuration.py
dlt/destinations/weaviate/naming.py
dlt/destinations/weaviate/weaviate_client.py
dlt/load/load.py
dlt/pipeline/pipeline.py
tests/common/storages/test_schema_storage.py
tests/common/test_destination.py
tests/extract/test_decorators.py
tests/load/pipeline/test_pipelines.py
tests/load/utils.py
tests/load/weaviate/test_naming.py
tests/load/weaviate/test_pipeline.py
tests/load/weaviate/test_weaviate_client.py
tests/pipeline/test_pipeline.py

please see commits for the changes.

allows empty dataset names in Weaviate config

---

dlt/load/load.py
tests/load/pipeline/test_replace_disposition.py
tests/load/pipeline/utils.py
tests/load/test_dummy_client.py

fixes the check for empty list of write dispositions to truncate

---

docs/website/docs/dlt-ecosystem/verified-sources/mux.md

Please review @AstrakhantsevaAA

Updated Mux Docs

---

docs/website/docs/dlt-ecosystem/verified-sources/matomo.md

Please review @AstrakhantsevaAA

Updated Matomo docs

---

docs/website/docs/dlt-ecosystem/verified-sources/jira.md

Please review the updated documentation @AstrakhantsevaAA. Thanks!

Updated Jira Docs.

---

docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md

please review @AstrakhantsevaAA

Updated Pipedrive docs

---

docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md

please review @AstrakhantsevaAA

Updated google sheets docs

---

docs/website/docusaurus.config.js
docs/website/package.json
docs/website/snipsync.config.yaml
docs/website/watch_snippets.js
docs/website/yarn.lock

Fixes the endless loop of snip sync by implementing a custom watcher.

fix snipsync endless loop

---

docs/website/docs/dlt-ecosystem/verified-sources/mongodb.md
docs/website/sidebars.js

Added MongoDB documentation.
- Fixes #...
- Closes #...

Added MongoDB documentation.

---

check-package.sh
dlt/common/configuration/inject.py
dlt/common/storages/file_storage.py
dlt/common/utils.py
dlt/destinations/duckdb/duck.py
dlt/extract/pipe.py
dlt/normalize/configuration.py
dlt/pipeline/pipeline.py
docs/snippets/reference/.dlt/config.toml
docs/snippets/reference/parallel_load/.dlt/config.toml
docs/snippets/reference/parallel_load/parallel_load.py
docs/snippets/reference/performance_chunking.py
docs/snippets/reference/performance_parallel_extract.py
docs/snippets/reference/test_reference_snippets.py
docs/website/docs/dlt-ecosystem/destinations/duckdb.md
docs/website/docs/reference/performance.md
docs/website/package-lock.json

it is also fixing several small issues with resolving configurations

updates performance docs

---

pyproject.toml

bumps to 0.3.17

---

docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md

Updates the SQL Database documentation.
- Fixes #...
- Closes #...

Update SQL Database docs.

---

dlt/common/data_types/type_helpers.py
dlt/common/json/__init__.py
dlt/common/libs/pydantic.py
dlt/common/schema/typing.py
dlt/extract/decorators.py
dlt/extract/exceptions.py
dlt/extract/pipe.py
dlt/extract/schema.py
dlt/extract/source.py
dlt/extract/typing.py
dlt/extract/validation.py
tests/common/schema/test_coercion.py
tests/common/test_pydantic.py
tests/extract/test_validation.py

WIP, needs tests
resolves #617

Pydantic validation

---

docs/website/docs/getting-started-snippets.py
docs/website/docs/getting-started.md
docs/website/requirements.txt

getting started db snippet fixes to work on SQLAlchemy 1.4 and 2.x

fixes db snippet for sqlalchemy 2.0

---

poetry.lock
pyproject.toml

Older version has a bug in multi-statement execution. See https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1696264702508729

Update min snowflake-connector version

---

docs/website/docs/examples/_examples-header.md
docs/website/docs/examples/incremental_loading/index.md
docs/website/docs/examples/transformers/index.md

Fixes the header section of the examples

fix examples header

---

.github/workflows/test_destination_synapse.yml

add synapse test workflow

---

docs/website/docs/dlt-ecosystem/verified-sources/workable.md

Updated Workable docs to new structure
- Fixes #...
- Closes #...

Updated Workable docs

---

docs/website/docs/dlt-ecosystem/verified-sources/stripe.md

Updated Stripe Docs!
- Fixes #...
- Closes #...

Updated Stripe Docs!

---

docs/website/docs/dlt-ecosystem/verified-sources/airtable.md
docs/website/docs/dlt-ecosystem/verified-sources/asana.md
docs/website/docs/dlt-ecosystem/verified-sources/chess.md
docs/website/docs/dlt-ecosystem/verified-sources/facebook_ads.md
docs/website/docs/dlt-ecosystem/verified-sources/github.md
docs/website/docs/dlt-ecosystem/verified-sources/google_analytics.md
docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
docs/website/docs/dlt-ecosystem/verified-sources/hubspot.md
docs/website/docs/dlt-ecosystem/verified-sources/jira.md
docs/website/docs/dlt-ecosystem/verified-sources/matomo.md
docs/website/docs/dlt-ecosystem/verified-sources/mongodb.md
docs/website/docs/dlt-ecosystem/verified-sources/mux.md
docs/website/docs/dlt-ecosystem/verified-sources/notion.md
docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md
docs/website/docs/dlt-ecosystem/verified-sources/salesforce.md
docs/website/docs/dlt-ecosystem/verified-sources/shopify.md
docs/website/docs/dlt-ecosystem/verified-sources/slack.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
docs/website/docs/dlt-ecosystem/verified-sources/strapi.md
docs/website/docs/dlt-ecosystem/verified-sources/stripe.md

so that all guides have the same structure, I added small fixes

[docs] small fixes

---

docs/website/docusaurus.config.js
docs/website/src/css/custom.css
docs/website/src/theme/Root.js
docs/website/static/img/SlackDark.svg
docs/website/static/img/SlackLight.svg

Updates the top bar in the docs to have nicer buttons

update docs top bar

---

dlt/destinations/duckdb/duck.py
dlt/destinations/motherduck/configuration.py
dlt/destinations/type_mapping.py
docs/website/docs/dlt-ecosystem/destinations/motherduck.md
poetry.lock
pyproject.toml
tests/helpers/dbt_tests/test_runner_dbt_versions.py
tests/load/duckdb/test_duckdb_table_builder.py
tests/load/pipeline/test_pipelines.py
tests/load/utils.py
tests/pipeline/test_dlt_versions.py

- bumps duckdb to 0.9.1
- adds instructions on how to troubleshoot motherduck by lowering the number of parallel workers

enables duckdb 0.9.1 and improves motherduck docs

---

docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md

Updated the google sheets docs with the latest info from the README.md. 
- Fixes #...
- Closes #...

Updated Google Sheets docs.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
README.md
docs/website/blog/2023-05-26-structured-data-lakes-through-schema-evolution-next-generation-data-platform.md
docs/website/blog/2023-06-21-open-api-spec-for-dlt-init.md
docs/website/blog/2023-08-21-dlt-lineage-support.md
docs/website/blog/2023-08-24-dlt-etlt.md
docs/website/blog/2023-09-05-mongo-etl.md
docs/website/blog/2023-09-26-verba-dlt-zendesk.md
docs/website/blog/2023-10-06-dlt-holistics.md
docs/website/blog/2023-10-10-data-product-docs.md
docs/website/blog/2023-10-16-first-data-warehouse.md
docs/website/blog/2023-10-19-dbt-runners.md
docs/website/blog/2023-10-23-arrow-loading.md
docs/website/docs/build-a-pipeline-tutorial.md
docs/website/docs/intro.md
docs/website/docusaurus.config.js

fix slack link

---

.github/workflows/test_destination_mssql.yml
dlt/common/data_writers/escape.py
dlt/common/data_writers/writers.py
dlt/common/libs/pyarrow.py
dlt/common/normalizers/json/relational.py
dlt/common/normalizers/utils.py
dlt/common/storages/load_storage.py
dlt/common/time.py
dlt/common/utils.py
dlt/extract/extract.py
dlt/normalize/configuration.py
dlt/normalize/items_normalizers.py
dlt/normalize/normalize.py
dlt/pipeline/pipeline.py
docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
pyproject.toml
tests/cases.py
tests/load/filesystem/test_aws_credentials.py
tests/load/pipeline/test_arrow_loading.py
tests/load/pipeline/utils.py
tests/pipeline/test_arrow_sources.py

Implements: https://github.com/dlt-hub/dlt/issues/700

Support all writer types in parquet normalizer

---

docs/website/blog/2023-10-30-data-modelling-tools.md

changed image for data modelling blog

---

docs/website/docs/walkthroughs/adjust-a-schema.md

fixed typo toml->yaml and add caution
- Fixes #...
- Closes #...

Docs: fix Adjust a Schema

---

dlt/destinations/snowflake/configuration.py

Fixes bug in snowflake connector

fix snowflake connector

---

docs/examples/CONTRIBUTING.md
docs/website/docs/examples/index.md
docs/website/sidebars.js

Docs: add Examples contributing doc

---

dlt/pipeline/track.py
docs/website/docs/dlt-ecosystem/destinations/snowflake.md
docs/website/docs/reference/telemetry.md
tests/pipeline/test_pipeline_trace.py

We want a few name hashes to telemetry (see docs edit in this PR for details). Motivation: to investigate if dataset, destinations and schema names change or stay constant for particular pipeline name

adds more name hashes to telemetry

---

pyproject.toml

bumps version to 0.3.25

---

docs/website/docs/dlt-ecosystem/verified-sources/airtable.md
docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
docs/website/docs/dlt-ecosystem/verified-sources/asana.md
docs/website/docs/dlt-ecosystem/verified-sources/chess.md
docs/website/docs/dlt-ecosystem/verified-sources/facebook_ads.md
docs/website/docs/dlt-ecosystem/verified-sources/filesystem.md
docs/website/docs/dlt-ecosystem/verified-sources/github.md
docs/website/docs/dlt-ecosystem/verified-sources/google_analytics.md
docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
docs/website/docs/dlt-ecosystem/verified-sources/hubspot.md
docs/website/docs/dlt-ecosystem/verified-sources/inbox.md
docs/website/docs/dlt-ecosystem/verified-sources/jira.md
docs/website/docs/dlt-ecosystem/verified-sources/matomo.md
docs/website/docs/dlt-ecosystem/verified-sources/mongodb.md
docs/website/docs/dlt-ecosystem/verified-sources/mux.md
docs/website/docs/dlt-ecosystem/verified-sources/notion.md
docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md
docs/website/docs/dlt-ecosystem/verified-sources/salesforce.md
docs/website/docs/dlt-ecosystem/verified-sources/shopify.md
docs/website/docs/dlt-ecosystem/verified-sources/slack.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
docs/website/docs/dlt-ecosystem/verified-sources/strapi.md
docs/website/docs/dlt-ecosystem/verified-sources/stripe.md
docs/website/docs/dlt-ecosystem/verified-sources/workable.md
docs/website/docs/dlt-ecosystem/verified-sources/zendesk.md

Docs: fix slack link

---

docs/website/docs/running-in-production/alerting.md
docs/website/docusaurus.config.js
docs/website/package-lock.json
docs/website/package.json
docs/website/sidebars.js
docs/website/src/css/custom.css
docs/website/tools/update_version_env.js

D#/devel docs

---

docs/website/blog/2023-11-27-dlt-data-lineage.md

The blog for the data lineage demo using load_info.

Adding the data lineage blog.

---

dlt/common/configuration/exceptions.py
dlt/common/exceptions.py
dlt/common/pipeline.py
dlt/common/utils.py
dlt/extract/extract.py
dlt/normalize/normalize.py
dlt/pipeline/exceptions.py
dlt/pipeline/pipeline.py
dlt/pipeline/trace.py
dlt/pipeline/typing.py
tests/common/configuration/test_configuration.py
tests/common/test_utils.py
tests/pipeline/test_pipeline.py
tests/pipeline/test_pipeline_trace.py

Extends step traces to add detailed exception information when pipeline step fails. Adds `load_id` to the `PipelineStepFailed`

adds exception traces

---

docs/website/docs/dlt-ecosystem/verified-sources/amazon_kinesis.md

Updated docs for "Kinesis Message Format"
- Fixes #...
- Closes #...

Updated docs for "Kinesis Message Format"

---

docs/website/docusaurus.config.js
docs/website/src/css/custom.css

Fix bug on docs site with sidebar going askew - see issue below.    
Enhancement added: user can hide/show the docs sidebar
- Fixes #...
- Closes #...
- Resolves #650
- PR is against `master` branch.  Should I have used `devel` instead?

Docs sidebar UI bug 650

---

.github/workflows/test_doc_snippets.yml
CONTRIBUTING.md
README.md
pyproject.toml

* bumps to next regular release 0.4.1
* updates the README with branch and release details

bumps dlt version to 0.4.1

---

docs/website/docs/dlt-ecosystem/verified-sources/hubspot.md

Into the Hubspot docs add a snippet, which shows how to extract particular properties of CRM objects.
Towards: https://github.com/dlt-hub/verified-sources/pull/311

docs(hubspot): update docs

---

dlt/common/destination/reference.py
dlt/sources/credentials.py
docs/website/docs/general-usage/credentials/config_providers.md
docs/website/docs/general-usage/credentials/configuration.md
docs/website/docs/general-usage/destination.md
docs/website/docs/general-usage/resource.md
docs/website/docs/general-usage/snippets/destination-snippets.py
docs/website/docs/general-usage/snippets/destination-toml.toml
docs/website/docs/running-in-production/running.md
docs/website/docs/utils.py
docs/website/docs/walkthroughs/create-a-pipeline.md
docs/website/docs/walkthroughs/create-new-destination.md
docs/website/sidebars.js

adds destination docs

---

pyproject.toml

- bumps dlt to next release 0.4.2

bumps dlt to version 0.4.2

---

docs/website/docs/examples/incremental_loading/code/zendesk-snippets.py

zendesk test data has slightly changed..

update zendesk snippets test

---

docs/website/blog/2024-01-08-streaming-pubsub-json-gcp.md

as written by https://github.com/dataroche

contrib blog post pubsub gcp

---

docs/website/blog/2024-01-12-dlt-dbt-runner-on-cloud-functions.md

Added dlt_dbt_runner article for blog

---

dlt/helpers/airflow_helper.py

Community member Hawkar Mahmod noticed we don't have some args in `add_run` function:
> I'm using the airflow helper, and would like to set the loader_file_format argument, which is normally passed to pipeline.run. However with Airflow we use the .add_run of the PipelineTaskGroup. Additional kwargs passsed into this method are provded to the airflow task rather than the pipeline run method. I've tried the GPT-4 helper but to no avail. Anyone have any idea where I can change the file format. I've looked at what add_run does and it does not pass any additional args to the pipeline.run call.
- Fixes #...
- Closes #...

Update airflow helper

---

docs/website/blog/2024-01-15-dlt-dbt-runner-on-cloud-functions.md

Added blog Article for dlt_dbt runner comparison
- Fixes #...
- Closes #...

Added article dlt_dbt_runner

---

docs/examples/google_sheets/.dlt/example.secrets.toml
docs/examples/google_sheets/google_sheets.py
docs/website/docs/examples/google_sheets/code/.dlt/config.toml
docs/website/docs/examples/google_sheets/code/.dlt/example.secrets.toml
docs/website/docs/examples/google_sheets/code/google_sheets-snippets.py
docs/website/docs/examples/google_sheets/index.md
docs/website/sidebars.js

Example for Google Sheets: https://www.notion.so/dlthub/Google-sheets-resource-in-4-lines-of-code-f7195ebf18034193ad6854e9ce36f4ea?pvs=4
- Fixes #...
- Closes #...

Examples: google sheets

---

docs/website/docs/dlt-ecosystem/verified-sources/shopify.md

Updated Shopify docs for Shopify partner API

---

docs/website/docs/dlt-ecosystem/verified-sources/kafka.md
docs/website/sidebars.js

Towards: https://github.com/dlt-hub/verified-sources/issues/273

docs(kafka): add Kafka source description

---

pyproject.toml

bumps to pre release 0.4.3a0

---

docs/website/docs/general-usage/customising-pipelines/removing_columns.md
docs/website/sidebars.js

Added documentation to remove columns

---

docs/website/docs/dlt-ecosystem/destinations/databricks.md
pyproject.toml

bumps to version 0.4.3

---

dlt/extract/incremental/__init__.py
tests/extract/test_incremental.py

This fixes two problems:
1. incremental set with `apply_hints` was not passed to resource function (but was used in the pipe)
2. setting primary key propagates value for incremental transform functions

passes incremental from apply hints to resource function

---

docs/website/docs/dlt-ecosystem/verified-sources/chess.md
docs/website/docs/dlt-ecosystem/verified-sources/github.md
docs/website/docs/dlt-ecosystem/verified-sources/hubspot.md
docs/website/docs/dlt-ecosystem/verified-sources/notion.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md

adds some additional documentation crosslinks

add some docs links

---

docs/website/blog/2023-10-30-data-modelling-tools.md

Clarification of the data modelling tools article in the blog. Updated info about GoodData capabilities, specifically support for "SQL dataset" and "ability to define primary/foreign keys with drag&drop". 
based on [discussion in the GoodData community Slack with Adrian]( https://gooddataconnect.slack.com/archives/C01LNE7NM1U/p1707321879710499?thread_ts=1707300044.914389&cid=C01LNE7NM1U)

Clarify info about GoodData in modelling tools article

---

dlt/destinations/impl/postgres/configuration.py
tests/load/postgres/test_postgres_client.py
tests/load/redshift/test_redshift_table_builder.py

* does not lowercase postgres and redshift database names

does not lowercase postgres and redshift database names

---

.github/workflows/get_docs_changes.yml
CONTRIBUTING.md

Florian from the community reached out saying we have a typing in Contribution guide. I run the document through Grammarly. Typings are minor. 
- Fixes #...
- Closes #...

Fix small typings in contributing guide

---

.github/workflows/test_destination_athena_iceberg.yml

Somehow the workflow for athena iceberg got an incorrect install command, this PR corrects this

add missing extra for athena iceberg test workflow

---

docs/website/docs/examples/incremental_loading/code/zendesk-snippets.py

Update the zendesk code example test because of updates in test account
- Fixes #...
- Closes #...

Fix zendesk example test

---

tests/extract/test_extract_pipe.py

Fixing the timing in the round robin test

change timing in round robin test

---

docs/website/docs/dlt-ecosystem/destinations/athena.md
docs/website/docs/dlt-ecosystem/destinations/bigquery.md
docs/website/docs/dlt-ecosystem/destinations/databricks.md
docs/website/docs/dlt-ecosystem/destinations/duckdb.md
docs/website/docs/dlt-ecosystem/destinations/index.md
docs/website/docs/dlt-ecosystem/destinations/motherduck.md
docs/website/docs/dlt-ecosystem/destinations/mssql.md
docs/website/docs/dlt-ecosystem/destinations/postgres.md
docs/website/docs/dlt-ecosystem/destinations/qdrant.md
docs/website/docs/dlt-ecosystem/destinations/redshift.md
docs/website/docs/dlt-ecosystem/destinations/snowflake.md
docs/website/docs/dlt-ecosystem/destinations/synapse.md
docs/website/docs/dlt-ecosystem/destinations/weaviate.md

These are selected files with grammar fixes from #994

Fix grammar in /docs/dlt-ecosystem/destinations/

---

docs/website/blog/2024-03-11-moving-away-from-segment.md

Adding the segment migration blog.

Adding the proposed segment migration blog

---

docs/website/docs/dlt-ecosystem/file-formats/insert-format.md
docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
docs/website/docs/dlt-ecosystem/file-formats/parquet.md
docs/website/docs/dlt-ecosystem/transformations/dbt/dbt.md
docs/website/docs/dlt-ecosystem/transformations/dbt/dbt_cloud.md
docs/website/docs/dlt-ecosystem/transformations/pandas.md
docs/website/docs/dlt-ecosystem/transformations/sql.md
docs/website/docs/dlt-ecosystem/verified-sources/amazon_kinesis.md
docs/website/docs/dlt-ecosystem/verified-sources/google_analytics.md
docs/website/docs/dlt-ecosystem/verified-sources/inbox.md
docs/website/docs/dlt-ecosystem/verified-sources/jira.md
docs/website/docs/dlt-ecosystem/verified-sources/kafka.md
docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md
docs/website/docs/dlt-ecosystem/verified-sources/slack.md

These are selected files with grammar fixes from #994 
The second batch. The first batch is #1070

Fix grammar in docs: batch 2

---

dlt/common/validation.py
tests/common/test_validation.py

Allows classes in typed dict and validates class instances, also respect unions

validates class instances in typed dict

---

dlt/helpers/airflow_helper.py
tests/helpers/airflow_tests/test_airflow_wrapper.py

Fixes https://github.com/dlt-hub/dlt/issues/407

feat(airflow): allow re-using sources in airflow wrapper

---

docs/website/docs/general-usage/incremental-loading.md

Docs/ Added a note on incremental behaviour

---

CONTRIBUTING.md

Updates the CONTRIBUTING.md to provide clearer instructions on how to propose changes or enhancements and how to report and fix bugs.

Clarify process for enhancements and bug fixes

---

dlt/cli/init_command.py
docs/website/docs/dlt-ecosystem/destinations/destination.md

Docs: fix custom destination 

---

docs/tools/.env.example
docs/tools/README.md
docs/tools/check_embedded_snippets.py
docs/tools/fix_grammar_gpt.py
docs/tools/requirements.txt
docs/tools/utils.py
mypy.ini

* Adds our gpt 3.5 docs helper to the tools

D#/gpt3.5 docs helper

---

dlt/common/schema/exceptions.py

Improve the output of the schema no upgrade path exception

improve no schema upgrade path exception

---

docs/tools/README.md
docs/tools/fix_grammar_gpt.py
docs/website/docs/dlt-ecosystem/destinations/destination.md
docs/website/docs/general-usage/destination.md
docs/website/docs/intro.md
docs/website/docs/walkthroughs/create-new-destination.md

Add example link to the custom destination page

---

.github/workflows/deploy_docs.yml

disable nightly docs deploy on forks

---

docs/website/docs/general-usage/schema.md

Update the schema documentation on how to use "direct" naming convention.
Issue: [#1177](https://github.com/dlt-hub/dlt/issues/1177)

Updated schema docs for naming convention

---

docs/website/docs/general-usage/schema.md

Docs: Corrected a snippet for naming = "direct"

---

docs/website/blog/2024-04-05-governance-democracy-mesh.md

add blog article shift left data democracy

---

dlt/destinations/impl/athena/athena.py

- Fixes #...
- Closes https://github.com/dlt-hub/dlt/issues/1226

fix athena iceberg's trailing location

---

dlt/common/data_writers/writers.py
dlt/destinations/impl/postgres/postgres.py
docs/website/docs/dlt-ecosystem/file-formats/csv.md
tests/load/pipeline/test_filesystem_pipeline.py

adds quoting style option to csv writer config

---

tests/helpers/dbt_tests/cases/profiles.yml
tests/helpers/dbt_tests/test_runner_dbt_versions.py

This pr fixes the dbt tests after the migration to the new postgres database. Also all snowflake datasets are dropped now to make the dbt snowflake tests run again.

fix dbt tests

---

dlt/destinations/path_utils.py
docs/website/docs/dlt-ecosystem/destinations/filesystem.md
tests/destinations/test_path_utils.py
tests/load/pipeline/test_filesystem_pipeline.py

This PR add seconds to filesystem layout placeholders

Add seconds and millisecond timestamps to filesystem date placeholders

---

docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
docs/website/package-lock.json

Updated documentation for the issue: 
How to configure MSSQL Destination with Windows Authentication
[#1250](https://github.com/dlt-hub/dlt/issues/1250)

Docs: Updated SQL documentation for windows authentication.

---

docs/website/docs/general-usage/schema.md

Added detections from 'detections.py' and linked 'detections.py'.

Docs: Updated autodetectors info

---

docs/tools/fix_grammar_gpt.py

Adds a chunking mechanism for the docs

fix gramar checker to respect the gpt context window

---

dlt/common/storages/file_storage.py
docs/examples/google_sheets/google_sheets.py
tests/common/storages/test_file_storage.py

fallbacks to copy on any OSError when doing hardlink

fallbacks to copy on any OSError when doing hardlink

---

dlt/common/destination/reference.py
dlt/destinations/impl/athena/athena.py
dlt/destinations/path_utils.py
dlt/sources/helpers/rest_client/paginators.py
pytest.ini
tests/load/filesystem/test_filesystem_client.py
tests/load/pipeline/test_athena.py
tests/load/pipeline/utils.py
tests/load/utils.py

* Adds layout tests for athena and athena iceberg
* Athena needs each table in its own subfolder, a folder with multiple tables and a prefix does not work, we raise an error now when this happens

fix athena edge case and adds layout tests for athena

---

docs/website/docs/general-usage/http/rest-client.md

This PR introduces a new section on PageNumberPaginator and updates OffsetPaginator with details on how to handle missing total items count in the response.

RESTClient: docs: add PageNumberPaginator, update OffsetPaginator

---

docs/website/blog/2024-05-07-on-orchestrators.md

A new blog post titled "On Orchestrators: You Are All Right, But You Are All Wrong Too".

Blog on orchestrators added

---

docs/website/docs/dlt-ecosystem/verified-sources/freshdesk.md
docs/website/sidebars.js

Added documentation for Freshdesk verified source.

Docs: Freshdesk documentation

---

docs/website/docs/running-in-production/running.md

Docs: Updated runnning docs with lhow to configure external logger

Docs: Updated runnning docs with how to configure external logger

---

docs/website/blog/2024-05-07-on-orchestrators.md
docs/website/docs/general-usage/destination.md

Configure multiple destinations in a pipeline

Added info about how to "Configure multiple destinations in a pipeline"

---

dlt/sources/helpers/rest_client/paginators.py

Correct the error output of the offset/limit paginators

improve paginator errors

---

dlt/common/schema/utils.py
dlt/extract/extractors.py
dlt/extract/hints.py
dlt/sources/helpers/rest_client/auth.py
dlt/sources/helpers/rest_client/client.py
dlt/sources/helpers/rest_client/detector.py
dlt/sources/helpers/rest_client/exceptions.py
dlt/sources/helpers/rest_client/paginators.py
pyproject.toml
tests/common/schema/test_merges.py
tests/common/test_validation.py
tests/load/weaviate/test_pipeline.py
tests/sources/helpers/rest_client/test_detector.py

1. exposes `merge_columns` in schema utils

exposes merge columns

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
docs/website/sidebars.js

Add rest_api verified source documentation

---

dlt/destinations/impl/mssql/__init__.py

1. limits mssql query size to fit network buffer

limits mssql query size to fit network buffer

---

docs/website/docs/dlt-ecosystem/destinations/snowflake.md

Modify the command to install `dlt[snowflake]`.
- Fixes #...
- Closes #...
Modify the pip command to install `dlt` for Snowflake.
pip install dlt[snowflake] → pip install "dlt[snowflake]"

fix command to install dlt

---

docs/website/docs/dlt-ecosystem/destinations/mssql.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md

1. makes it up to data with code
2. TODO: a guide for granular (per table) configuration with toml

[master] improves sql database docs

---

pyproject.toml

Adds missing typing classifier and updates maintainers in pyproject

add typing classifier and update maintainers in pyproject

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md

rest_api: docs: Mention JSONPath in resolve conf

---

docs/website/docs/dlt-ecosystem/destinations/filesystem.md

This PR is based on https://github.com/dlt-hub/dlt/pull/1385

Update filesystem docs with auto mkdir config

---

docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md

fixes `sql_database` snippets linting

fixes sql_database snippets linting

---

.github/workflows/test_destination_qdrant.yml

QDrant tests are broken, since this destination is not as high a priority, we disable the tests for now.

disable qdrant tests

---

docs/website/docs/reference/frequently-asked-questions.md

Removed absolute links to documentation pages from FAQ

---

docs/website/docs/general-usage/incremental-loading.md

Documentation: Added note for indexing

---

docs/website/docs/general-usage/destination-tables.md
docs/website/docs/general-usage/schema-contracts.md
tests/pipeline/test_schema_contracts.py

Update the docs on how to work with schema contracts and existing tables and columns

docs for loading with contracts to existing tables

---

docs/website/blog/2024-06-19-scd2-and-incremental-loading.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
docs/website/docs/general-usage/incremental-loading.md

Added slowly changing dimensions and incremental loading blog article

Added slowly changing dimensions and incremental loading blog article

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
docs/website/docs/general-usage/http/rest-client.md

Docs: cover custom authentication, rework paginators section

---

docs/website/blog/2024-06-21-google-forms-to-notion.md

Added blog google forms to notion

Added blog google-forms-to-notion

---

dlt/pipeline/pipeline.py

fix: `Pipeline.sql_client` credentials forwarding

---

docs/website/docs/dlt-ecosystem/verified-sources/stripe.md

removed metrics resource from docs

Docs: remove metrics resource from stripe

---

docs/website/blog/2024-02-06-practice-api-sources.md

Updated API playground article
- Added 16 new API's
- Rest API example pipeline
- DTC learners showcase

Updated API playground article

---

docs/website/docs/dlt-ecosystem/destinations/duckdb.md

docs: Fixed markdown issue in duckdb.md

---

docs/website/docs/tutorial/grouping-resources.md

Fixed import paginate on dynamic_resources section.
- Fixes #...
- Closes #...

Update grouping-resources.md docs

---

docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
docs/website/sidebars.js

Added Postgres replication verified sources docs

Added Postgres replication verified sources docs

---

.github/workflows/test_doc_snippets.yml
.github/workflows/test_local_destinations.yml
dlt/common/destination/reference.py
dlt/destinations/impl/qdrant/configuration.py
dlt/destinations/impl/qdrant/exceptions.py
dlt/destinations/impl/qdrant/factory.py
dlt/destinations/impl/qdrant/qdrant_client.py
dlt/load/load.py
dlt/pipeline/pipeline.py
docs/examples/qdrant_zendesk/qdrant_zendesk.py
docs/tools/prepare_examples_tests.py
tests/conftest.py
tests/load/pipeline/test_arrow_loading.py
tests/load/pipeline/test_restore_state.py
tests/load/qdrant/test_pipeline.py
tests/load/utils.py

* Fixes issues with qdrant state restore
* Support local qdrant
* Test both local and server qdrant (same tests as weaviate)
*  server qdrant runs in docker in CI instead of cloud
- Resolves https://github.com/dlt-hub/dlt/issues/1337

Fix/qdrant tests in CI

---

docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md

* Document sql source reflection level and type adapter
* fix snippet type
* updates sql_database docs
---------
- Fixes #...
- Closes #...

Document sql source reflection level and type adapter (#1467)

---

docs/website/blog/2024-07-08-how-dlt-uses-apache-arrow.md

Added blog post with a canonical link:
https://jorritsandbrink.substack.com/p/how-dlt-uses-apache-arrow-for-fast-pipelines

Added blog how-dlt-uses-apache-arrow

---

docs/website/blog/2024-07-11-how-dlt-uses-apache-arrow.md

Added how dlt uses arrow by jorrit

Added how dlt uses arrow by jorrit

---

dlt/common/pipeline.py
dlt/destinations/impl/snowflake/configuration.py
dlt/destinations/impl/snowflake/snowflake.py
dlt/destinations/impl/snowflake/sql_client.py
dlt/destinations/job_client_impl.py
dlt/destinations/sql_client.py
dlt/load/load.py
docs/website/docs/dlt-ecosystem/destinations/snowflake.md
tests/load/pipeline/test_snowflake_pipeline.py
tests/load/snowflake/test_snowflake_client.py

Adds query tagging for Snowflake, see the docs update for details.

query tagging for snowflake

---

docs/website/docs/dlt-ecosystem/verified-sources/hubspot.md

Updated hubspot documentation for error len(properties)> 2000

Updated hubspot documentation

---

dlt/helpers/streamlit_app/utils.py
tests/helpers/streamlit_tests/test_streamlit_show_resources.py

fixes mypy errors during development

---

docs/website/tools/preprocess_docs.js

restrict tuba links to 10 per page

---

dlt/sources/helpers/rest_client/paginators.py

- Fixes  https://github.com/dlt-hub/dlt/issues/1632

Allows using JSONResponsePaginator in place of JSONLinkPaginator

---

docs/website/docs/intro.md
docs/website/docs/reference/installation.md

Following feedback received at pyeurope, I have added a hint about venv on the intro page and updated the installation page.

add venv hint on first page and update installation page

---

dlt/sources/helpers/rest_client/client.py
tests/sources/helpers/rest_client/test_client.py

- Resolves https://github.com/dlt-hub/dlt/issues/1593

Feat/1593 rest_client: allow setting of request kwargs

---

docs/website/docs/general-usage/incremental-loading.md

This documents the current feature set of dlt. 
In parallel, we're working on fixes for processing Arrow and may also allow dlt to load None cursor_path values incrementally.
- https://github.com/dlt-hub/dlt/issues/1571
- discussion: https://github.com/dlt-hub/dlt/pull/1576

Docs/1571 docs on handling NULL values at incremental cursor path

---

.github/weaviate-compose.yml
.github/workflows/test_destination_clickhouse.yml
.github/workflows/test_destination_dremio.yml
.github/workflows/test_doc_snippets.yml
.github/workflows/test_local_destinations.yml

Test wether we can switch from docker-compose to docker compose without other changes in the tests.

switch to docker compose subcommand

---

dlt/common/destination/reference.py
docs/website/docs/general-usage/naming-convention.md
tests/common/test_destination.py

Now there is an option to control the dataset name normalization separately. `enable_dataset_name_normalization=true`

Add enable_dataset_name_normalization option

---

docs/website/netlify.toml

This PR adds redirects for configuration pages restructure in #1508

Docs: handle renamed credential docs pages

---

docs/examples/parent_child_relationship/parent_child_relationship.py
docs/examples/parent_child_relationship/test_parent_child_relationship.py

Added example to load parent table keys into child table records.
issue- #1589

Add custom parent-child relationships example

---

docs/examples/custom_destination_lancedb/custom_destination_lancedb.py
docs/website/docs/general-usage/incremental-loading.md

Refined documentation with minor improvements
- Fixes #...
- Closes #1759

Refined documentation with minor improvements

---

docs/website/docs/reference/performance.md

Updated performance docs for `file_max_items` and `file_max_bytes`
- Closes #1588

Updated performance docs for parameters file_max_items & bytes

---

docs/website/docs/general-usage/credentials/setup.md

Fix link in credentials

---

docs/website/docs/dlt-ecosystem/verified-sources/index.md

remove doccard list

---

docs/website/docs/dlt-ecosystem/verified-sources/index.md
docs/website/tools/preprocess_docs.js
docs/website/tools/update_versions.js

master: fix docs deployment 3

---

docs/website/docs/dlt-ecosystem/destinations/athena.md
docs/website/docs/dlt-ecosystem/destinations/bigquery.md
docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
docs/website/docs/dlt-ecosystem/destinations/databricks.md
docs/website/docs/dlt-ecosystem/destinations/destination.md
docs/website/docs/dlt-ecosystem/destinations/dremio.md
docs/website/docs/dlt-ecosystem/destinations/duckdb.md
docs/website/docs/dlt-ecosystem/destinations/filesystem.md
docs/website/docs/dlt-ecosystem/destinations/index.md
docs/website/docs/dlt-ecosystem/destinations/lancedb.md
docs/website/docs/dlt-ecosystem/destinations/motherduck.md
docs/website/docs/dlt-ecosystem/destinations/mssql.md
docs/website/docs/dlt-ecosystem/destinations/postgres.md
docs/website/docs/dlt-ecosystem/destinations/qdrant.md
docs/website/docs/dlt-ecosystem/destinations/redshift.md
docs/website/docs/dlt-ecosystem/destinations/snowflake.md
docs/website/docs/dlt-ecosystem/destinations/sqlalchemy.md
docs/website/docs/dlt-ecosystem/destinations/synapse.md
docs/website/docs/dlt-ecosystem/destinations/weaviate.md
docs/website/docs/dlt-ecosystem/file-formats/csv.md

Grammar check for pages 40 - 60

Docs grammar, pages 40-60

---

docs/website/docs/dlt-ecosystem/file-formats/insert-format.md
docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
docs/website/docs/dlt-ecosystem/file-formats/parquet.md
docs/website/docs/dlt-ecosystem/verified-sources/_source-info-header.md
docs/website/docs/dlt-ecosystem/verified-sources/amazon_kinesis.md
docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
docs/website/docs/dlt-ecosystem/verified-sources/github.md
docs/website/docs/dlt-ecosystem/verified-sources/google_analytics.md
docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
docs/website/docs/dlt-ecosystem/verified-sources/inbox.md
docs/website/docs/dlt-ecosystem/verified-sources/jira.md
docs/website/docs/dlt-ecosystem/verified-sources/kafka.md
docs/website/docs/dlt-ecosystem/verified-sources/matomo.md
docs/website/docs/dlt-ecosystem/verified-sources/notion.md
docs/website/docs/dlt-ecosystem/verified-sources/openapi-generator.md
docs/website/docs/dlt-ecosystem/verified-sources/personio.md
docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md
docs/website/docs/dlt-ecosystem/verified-sources/scrapy.md
docs/website/docs/dlt-ecosystem/verified-sources/slack.md
docs/website/docs/dlt-ecosystem/verified-sources/stripe.md

docs: fixing grammar files 60-80

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md

Docs: rest_api: document `processing_steps`

---

tests/sources/helpers/rest_client/test_client.py
tests/sources/rest_api/integration/test_offline.py

Just a small cleanup.
- Resolves #1890

refactors Session mocking in RESTClient tests 

---

tests/cli/test_init_command.py

This fixes our crashing CI. Trace: https://github.com/dlt-hub/dlt/actions/runs/11084013066/job/30798875038#step:11:1326
Requires https://github.com/dlt-hub/verified-sources/pull/571 to be merged into master.

fix: corrects test suite

---

docs/website/docs/dlt-ecosystem/destinations/weaviate.md

PR #746 moved the location of `weaviate/README.md`. This PR adjusts sources to changes.

Update weaviate reference

---

docs/website/docs/dlt-ecosystem/verified-sources/airtable.md
docs/website/docs/dlt-ecosystem/verified-sources/asana.md
docs/website/docs/dlt-ecosystem/verified-sources/chess.md
docs/website/docs/dlt-ecosystem/verified-sources/facebook_ads.md
docs/website/docs/dlt-ecosystem/verified-sources/freshdesk.md
docs/website/docs/dlt-ecosystem/verified-sources/google_ads.md
docs/website/docs/dlt-ecosystem/verified-sources/hubspot.md
docs/website/docs/dlt-ecosystem/verified-sources/index.md
docs/website/docs/dlt-ecosystem/verified-sources/mongodb.md
docs/website/docs/dlt-ecosystem/verified-sources/mux.md
docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
docs/website/docs/dlt-ecosystem/verified-sources/salesforce.md
docs/website/docs/dlt-ecosystem/verified-sources/shopify.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database/index.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database/setup.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database/troubleshooting.md
docs/website/docs/dlt-ecosystem/verified-sources/sql_database/usage.md
docs/website/docs/dlt-ecosystem/verified-sources/strapi.md
docs/website/docs/dlt-ecosystem/verified-sources/workable.md
docs/website/docs/dlt-ecosystem/verified-sources/zendesk.md

Grammar checker for pages 80 to 100

fix grammar pages 80-100

---

docs/website/docs/general-usage/credentials/setup.md

Added the missing `return` to `load_config()`

Docs: fix the code snippet in credentials/setup.md

---

dlt/sources/sql_database/schema_types.py

fix: UUIDs are not an unknown data type (logging)

---

dlt/common/runtime/anon_tracker.py
dlt/sources/pipeline_templates/.dlt/config.toml
docs/website/netlify.toml

Docs: fix the broken telementry docs link

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md

This PR updated `rest_api` source documentation for multiple path parameters resolving. 
Feature PR: #1923 
Issue: #1922

Docs: add section on resolving multiple path parameters

---

docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-airflow-composer.md

The original urls is broken. I assume this is the correct page to link to?
---
just a small url

Update url in deploy-with-airflow-composer.md

---

dlt/destinations/impl/bigquery/bigquery.py
dlt/destinations/impl/bigquery/bigquery_adapter.py
dlt/destinations/impl/duckdb/configuration.py
dlt/destinations/impl/motherduck/configuration.py
docs/website/docs/dlt-ecosystem/destinations/motherduck.md
tests/load/bigquery/test_bigquery_table_builder.py
tests/load/duckdb/test_motherduck_client.py

adds bigquery partition expiration and  motherduck connection string

---

dlt/common/utils.py
dlt/sources/rest_api/__init__.py
dlt/sources/rest_api/config_setup.py
dlt/sources/rest_api/utils.py

Move `exclude_keys()` to `dlt.common.utils`

---

docs/website/docs/dlt-ecosystem/verified-sources/index.md

Fix header to exclude

---

dlt/destinations/impl/databricks/configuration.py
docs/website/docs/dlt-ecosystem/destinations/databricks.md
tests/load/databricks/test_databricks_configuration.py

Add user agent for Databricks

---

dlt/common/configuration/specs/azure_credentials.py

Fix an incorrect missing dependency error 

---

docs/website/docusaurus.config.js

Removing hardcoded analytics for docs site.

remove ga add tm

---

docs/examples/partial_loading/partial_loading.py

make title shorter

---

docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-modal.md

Simplified this section since we updated our proxy ip interface.
I also noticed the code snippets are not being indented properly on the dev website, do you know what's going on?

simplify advanced section

---

tests/conftest.py

Try to clean up github actions logs

attempt to disable google discovery cache logging for tests

---

docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md

Updated sql_database documentation for resource usage
- Closes #2069

Updated sql_database documentation for resource usage

---

docs/website/docs/dlt-ecosystem/destinations/filesystem.md
mypy.ini
pyproject.toml
tests/load/test_read_interfaces.py

* azure docs update
* bump for alpha release

azure account host docs

---

docs/website/docs/dlt-ecosystem/destinations/redshift.md

Updated the Redshift destination documentation to include a note on selecting the appropriate driver.

Updated Redshift documentation with a note on driver selection

---

docs/website/docs/dlt-ecosystem/destinations/clickhouse.md

Fix very minor typo in the info block for Datasets

Fix minor typo :3

---

docs/website/docs/dlt-ecosystem/destinations/filesystem.md

Changes an example which doesn't work to one that does in this section https://dlthub.com/docs/dlt-ecosystem/destinations/filesystem#available-layout-placeholders

🐛 Fix parquet layout example in the docs

---

dlt/common/libs/pyarrow.py

Fix formatting

---

dlt/extract/incremental/__init__.py
dlt/sources/sql_database/__init__.py
dlt/sources/sql_database/helpers.py
dlt/sources/sql_database/schema_types.py
tests/load/sources/sql_database/sql_source.py
tests/load/sources/sql_database/test_helpers.py
tests/load/sources/sql_database/test_sql_database_source.py
tests/load/sources/sql_database/test_sql_database_source_all_destinations.py

* recognizes ARRAY data type and converts to nested, fixes minimal nested types handling for sqlalchemy backend
* ports and closes https://github.com/dlt-hub/verified-sources/pull/547 by @vivingo

recognizes ARRAY data type and converts to nested, fixes minimal nested types handling for sqlalchemy backend

---

.github/ISSUE_TEMPLATE/bug_report.yml

Add python 3.12 and 3.13 to bug report template

---

dlt/common/runners/venv.py
dlt/destinations/impl/mssql/configuration.py
dlt/helpers/dbt/__init__.py
dlt/helpers/dbt/dbt_utils.py
dlt/helpers/dbt/profiles.yml
dlt/pipeline/dbt.py
docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
docs/website/docs/dlt-ecosystem/destinations/synapse.md
tests/helpers/dbt_tests/test_runner_dbt_versions.py
tests/load/pipeline/test_dbt_helper.py
tests/load/pipeline/test_snowflake_pipeline.py

* fixes #2226
* also fixes `uv` that accepted pre-release packages when creating dbt envs
based on #2241

#2226 enables dbt 1.9

---

pyproject.toml

bumps dlt to 1.6.0

---

docs/website/docs/plus/getting-started/installation.md

Update dlt+ installation page

---

docs/website/docs/plus/intro.md
docs/website/docs/plus/production/observability.md
docs/website/docs/plus/production/runners.md
docs/website/sidebars.js

add production docs

---

dlt/sources/helpers/rest_client/paginators.py

Correct type hints of construction parameter total_path for OffsetPaginator and PageNumberPaginator

---

docs/website/docs/general-usage/http/rest-client.md

docs: Add HeaderCursorPaginator documentation to RESTClient

---

dlt/common/runtime/run_context.py
tests/common/runtime/test_run_context.py

#2282 fix import run dir module

---

docs/website/docs/reference/installation.md

- Python 3.9 is the minimum supported version of Python
Updates the documentation to for the [1.6.1 version of dlt](https://github.com/dlt-hub/dlt/releases/tag/1.6.1).

update minimum supported Python version installation.md

---

docs/website/docs/plus/core-concepts/cache.md
docs/website/docs/plus/core-concepts/datasets.md
docs/website/docs/plus/core-concepts/profiles.md
docs/website/docs/plus/core-concepts/project.md
docs/website/docs/plus/features/ai.md
docs/website/docs/plus/features/projects.md
docs/website/docs/plus/features/quality/tests.md
docs/website/docs/plus/getting-started/tutorial.md

[docs] adds corrections dlt plus docs

---

docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md

Updated sql database docs for selecting tables and columns via config.toml

Updated sql database docs for selecting tables and columns via config.toml

---

dlt/destinations/job_client_impl.py

Copied from https://github.com/dlt-hub/dlt/pull/2316 by @xneg.
This PR limits the state and schema retrieval queries to 1, which prevents problems on bigquery in some cases.

limit schema and state retrieval queries

---

docs/website/docusaurus.config.js
docs/website/tools/update_versions.js

Re-enables versions on docusaurus 3

docs: re-enable versions

---

dlt/common/configuration/specs/aws_credentials.py
dlt/destinations/impl/filesystem/sql_client.py

adds support for http and path style for filesystem sql_client with s3

---

docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md

Comment consistently

---

pyproject.toml

bumps dlt to 1.9.0

---

dlt/cli/command_wrappers.py
dlt/cli/init_command.py
dlt/cli/plugins.py
docs/website/docs/reference/command-line-interface.md
tests/cli/test_init_command.py

Follows #2426. I mangled my git history with rebase :(

list-destination flag added

---

dlt/destinations/impl/bigquery/bigquery.py
dlt/destinations/impl/bigquery/configuration.py
docs/website/docs/dlt-ecosystem/destinations/bigquery.md
tests/load/bigquery/test_bigquery_client.py

- Add ignore_unknown_values option to BigQuery destination

add ignore_unknown_values option to BigQuery destination

---

dlt/sources/sql_database/__init__.py
docs/website/docs/dlt-ecosystem/destinations/bigquery.md

Replaces a singular instance in the BigQuery documentation where _Redshift_ was written, where this should have been _BigQuery_.
Fixes #2484

Docs: BigQuery incorrect reference

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md

docs: update incremental loading section in REST API documentation

---

dlt/extract/incremental/__init__.py
dlt/extract/items_transform.py
tests/extract/test_extract.py
tests/extract/test_incremental.py

Preserve type of emtpy lists in incremental to allow to materialize empty resources

---

docs/website/docs/dlt-ecosystem/llm-tooling/cursor-restapi.md
docs/website/sidebars.js

Added documentation for building Rest API with cursor

[WIP]Docs for building Rest API with cursor

---

dlt/common/libs/cryptography.py
dlt/destinations/impl/snowflake/configuration.py
docs/website/docs/dlt-ecosystem/destinations/snowflake.md
tests/load/snowflake/test_snowflake_configuration.py

fixes #2192 
NOTE: failed tests are flukes. some timeouts on backends

#2192 - adds base64 encoded PEM, private_key_path, improves docs

---

docs/website/docs/plus/ecosystem/ms-sql.md

Add instructions on how to make sure the `_DLT_DELETED` and `_DLT_SYS_CHANGE_VERSION` columns are present on the initial load for the MS SQL Change Tracking source.

Docs: add documentation for CT columns

---

docs/website/docs/general-usage/dataset-access/marimo.md
docs/website/sidebars.js

added marimo to index

---

tests/cli/test_config_toml_writer.py

fix: update placeholder values in TOML writer tests

---

dlt/destinations/impl/snowflake/sql_client.py
docs/website/docs/dlt-ecosystem/destinations/snowflake.md
docs/website/docs/reference/performance_snippets/.dlt/config.toml
tests/load/snowflake/test_snowflake_client.py

Sets explicit autocommit on Snowflake connection, see PR #2480

explicit snowflake autocommit

---

dlt/destinations/impl/clickhouse/configuration.py
docs/website/docs/dlt-ecosystem/destinations/clickhouse.md

Fixes and improves clickhouse configuration docstring and docs page

slightly clarify clickhouse docs

---

docs/website/docs/dlt-ecosystem/llm-tooling/cursor-restapi.md

Fix some typos in the REST API Sources with Cursor docs
- Fixes: NA
- Closes: NA
- Resolves: NA
Found some typos while reading [REST API Sources with Cursor](https://dlthub.com/docs/devel/dlt-ecosystem/llm-tooling/cursor-restapi)

fix some typos in cursor-restapi docs

---

Makefile
dlt/helpers/airflow_helper.py
tests/helpers/airflow_tests/test_airflow_wrapper.py

Makes Airflow helpers compatible up to 2.10.x
see #2601

removes airflow Airflow DummyOperator import

---

docs/website/docs/general-usage/destination-tables.md

Updated section reference destination tables. Added info about dlt's internal tables

Added info about dlt's internal tables

---

docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md

Added section using xmin for Change Data Capture (CDC) to pg_replication docs
- Fixes #2376 
- Closes #2376
- Resolves #2376

Added section using xmin for Change Data Capture (CDC) to pg_replication docs

---

docs/website/docs/dlt-ecosystem/transformations/add-map.md
docs/website/docs/dlt-ecosystem/transformations/dbt/dbt.md
docs/website/docs/dlt-ecosystem/transformations/dbt/dbt_cloud.md
docs/website/docs/dlt-ecosystem/transformations/python.md
docs/website/docs/dlt-ecosystem/transformations/sql.md
docs/website/sidebars.js

Added new documentation named "Transform data with add_map.

Added Transform data with add_map documentation

---

docs/website/docs/dlt-ecosystem/transformations/add-map.md
docs/website/docs/plus/features/projects.md
docs/website/docs/walkthroughs/add_credentials.md

fixes wrong docs links that came from nowhere

---

dlt/helpers/ibis.py

Both do not work and have been making tests fail, this PR officially disables them for now.

disables synapse and databricks ibis connector

---

CONTRIBUTING.md
README.md
docs/website/docs/dlt-ecosystem/verified-sources/inbox.md

README / CONTRIB are more specific which kind of contributions we accept and how to do it
also moves a doc snippet from verified sources

changes contrib and README

---

dlt/common/data_writers/writers.py
dlt/destinations/impl/databricks/sql_client.py
poetry.lock
pyproject.toml
tests/pipeline/test_pipeline_extra.py

Arrow was tolerating null values in non null columns. Additional check got added:
fixes #2681 
fixes #1807
fixes #2475  (removes cffi version of psycopg2)
also:
fixes flaky test on databricks (concurrent writes to delta tables - does a retry)

2681 - fixes null on non null column arrow

---

dlt/cli/pipeline_command.py
dlt/cli/plugins.py
dlt/helpers/studio/app.py
dlt/helpers/studio/runner.py
docs/website/docs/reference/command-line-interface.md
poetry.lock
pyproject.toml

This PR opens the correct page for the marimo app when using the "pipeline show" command.

open correct page in marimo app for "pipeline show" command

---

.github/workflows/main.yml
docs/examples/chess/chess.py
docs/examples/chess_production/chess_production.py
docs/website/docs/tutorial/load-data-from-an-api.md

This fixes the CI setup to always check the docs snippets, even if the PR is from a fork.

alway test docs snippets, not only after authorization

---

dlt/cli/__init__.py
dlt/cli/ai_command.py
dlt/cli/command_wrappers.py
dlt/cli/init_command.py
dlt/cli/pipeline_files.py
dlt/cli/plugins.py
dlt/sources/_single_file_templates/vibe_rest_api_pipeline.py
mypy.ini
tests/cli/common/test_cli_invoke.py
tests/cli/common/test_telemetry_command.py
tests/cli/conftest.py
tests/cli/test_init_command.py
tests/cli/utils.py
tests/extract/test_decorators.py
tests/utils.py

```
dlt init dlthub:notion duckdb
```
will use special rest api sources template to generate empty notion pipeline (full AST names rewrite), download additional cursor rules and specific notion docs and snippers

allows to copy files from vibe-hub repo

---

docs/website/docs/dlt-ecosystem/file-formats/_set_the_format.mdx

Updated the file format docs with working methods to select file format.
- Closes #2641

Docs: Updated the file format docs.

---

dlt/sources/rest_api/config_setup.py
tests/sources/rest_api/configurations/test_configuration.py

rest_api: allow processing multiple DltResource instances

---

Makefile

cleans dist folder before publish

cleans dist folder before publish

---

dlt/common/data_writers/configuration.py
dlt/common/data_writers/writers.py
docs/website/docs/dlt-ecosystem/file-formats/csv.md
docs/website/docs/dlt-ecosystem/file-formats/insert-format.md
docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
docs/website/docs/dlt-ecosystem/file-formats/parquet.md
tests/libs/test_csv_writer.py

Extend CSV quoting options in CsvWriter

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api/advanced.md
docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
tests/sources/rest_api/integration/test_offline.py

docs: add docs for headers configuration

---

docs/website/docs/tutorial/playground.mdx

Updated description for wasm playground

---

docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md

change secrets.toml file to sources.rest_api_pipeline.github

---

docs/website/docs/dlt-ecosystem/destinations/motherduck.md

Added DuckLake setup instructions to the MotherDuck destination docs

Add DuckLake setup section to documentation

---

dlt/sources/filesystem/readers.py
tests/sources/filesystem/test_config_sections.py
tests/sources/rest_api/test_config_sections.py
tests/sources/sql_database/test_config_sections.py

Fixes the configuration resolution for the filesystem readers and adds basic tests for all sources

fix filesystem config section

---

docs/website/docs/dlt-ecosystem/destinations/databricks.md
docs/website/docs/dlt-ecosystem/destinations/filesystem.md

Added troubleshooting steps for Databricks and updated filesystem docs for using OneLake as a destination.
Slack thread : [here](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1750025017725709)

Added troubleshooting steps for Databricks and other minor updates

---

docs/website/docs/general-usage/dataset-access/dataset.md

Adds simple migration guide for updated ibis relation.

add ibis dataset migration guide

---

docs/website/docs/general-usage/resource.md

link to add_map and add_yield_map usage example

---

dlt/common/schema/schema.py
tests/common/schema/test_inference.py

skips inferring incomplete column when already incomplete

---

dlt/sources/helpers/rest_client/client.py
tests/sources/helpers/rest_client/test_client.py
tests/sources/rest_api/conftest.py

fix: restclient: handle null data in response

---

docs/website/docs/dlt-ecosystem/llm-tooling/llm-native-workflow.md

This PR updates the LLM workflow docs that only included the Cursor example. It now mentions that there other options and provides Cursor and Continue examples in certain configuration tips.

Docs: llm workflow docs updated

---

docs/website/docs/dlt-ecosystem/llm-tooling/llm-native-workflow.md

This PR adds a small adjustment in the page description of the `llm-native-workflow.md` file in docs.

Docs: Page description fix in llm native workflow

---

docs/website/docs/walkthroughs/create-a-pipeline.md

pip install marimo -> dlt[workspace]

---

pyproject.toml
uv.lock

Prepares 1.16 release with version bump and full ci run.

bumps to version 1.16

---

.github/workflows/lint.yml
docs/website/README.md
docs/website/docusaurus.config.js
docs/website/package-lock.json
docs/website/package.json
docs/website/worker.js
docs/website/wrangler.jsonc

TLDR
We want to deploy our docs to cloudflare.
Pre-Merge ToDos
Post-Merge ToDos
- [ ] Switch of netlify project

Docs Cloudflare worker deployment

---

docs/website/docs/dlt-ecosystem/transformations/index.md
docs/website/docs/dlt-ecosystem/verified-sources/index.md

Fixes 4 more links in documentation.

Fix remaining routing problems in cloudflare setup, part 2

---

pyproject.toml
uv.lock

bump to version 1.17.1

---

dlt/destinations/impl/databricks/databricks.py
dlt/destinations/impl/databricks/databricks_adapter.py
dlt/destinations/impl/databricks/factory.py
docs/website/docs/dlt-ecosystem/destinations/databricks.md
tests/load/databricks/test_databricks_adapter.py

Adds clustering, partitioning, table properties, and Apache Iceberg support to the Databricks destination adapter.
New Parameters:
- cluster: Column list for column clustering or "AUTO" for automatic optimization
- partition: Table partitioning by specified columns
- table_properties: Delta Lake optimization settings (TBLPROPERTIES)
- table_format: Support for "DELTA" and "ICEBERG" table formats
Key Features:
- Performance optimization through clustering and partitioning for downstream queries
- Ability to set data skipping with delta.dataSkippingStatsColumns
- Closes #2863

[Databricks destination] Feat/2863 databricks table optimization
